#!/bin/bash

set -o nounset
set -o errexit
set -o pipefail
stty -echoctl # Hide ^C

function quit_kubeshell() {
	echo -e "\rExiting kubeshell..."
	exit 0
}

trap quit_kubeshell SIGINT

while true; do
	read -erp "kubeshell$ " kubectl_command

	case "$kubectl_command" in 
		"exit"|"quit"|":q")
			quit_kubeshell
			;;
		*)
			# shellcheck disable=SC2086
			kubectl $kubectl_command
			;;
	esac
done
