#!/bin/bash

set -o nounset
set -o errexit
set -o pipefail

while true; do
	echo -n "kubeshell $ "	
	read kubectl_command

	case "$kubectl_command" in 
		"exit")
			exit
			;;
		*)
			kubectl $kubectl_command
			;;
	esac
done
